### ISSUE TITLE
gulp clean && gulp build did not run

### ISSUE THREAD

**Issue by QiuMing** [solairerove/blog-app#27]
Hello ,I have  meet some problem while learn your angular app
```
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
File 'F:/boot-demo/blog-app/src/main/frontend/gulpfile.ts' is not under 'rootDir' 'F:/boot-demo/blog-app/src/main/frontend/app'. 'rootDir' is expected to contain all source files. (6059)
gulpfile.ts (4,14): Cannot find name 'require'. (2304)
gulpfile.ts (5,13): Cannot find name 'require'. (2304)
gulpfile.ts (6,13): Cannot find name 'require'. (2304)
gulpfile.ts (7,20): Cannot find name 'require'. (2304)
gulpfile.ts (9,16): Cannot find name 'require'. (2304)
    at getOutput (F:\boot-demo\blog-app\src\main\frontend\node_modules\ts-node\src\index.ts:253:17)
    at F:\boot-demo\blog-app\src\main\frontend\node_modules\ts-node\src\index.ts:263:16
    at Object.compile (F:\boot-demo\blog-app\src\main\frontend\node_modules\ts-node\src\index.ts:398:17)
    at Module.m._compile (F:\boot-demo\blog-app\src\main\frontend\node_modules\ts-node\src\index.ts:299:46)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .ts] (F:\boot-demo\blog-app\src\main\frontend\node_modules\ts-node\src\index.ts:302:14)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

I have  run  
```
npm install typescript-register ts-node
```
before this , and my tsc version  is 1.8.10. And I have search this error in google but did not get help.
Do you know why ?

**Comment by solairerove** [comment]
lol. first human, who open issue. get us some time. we will check this. ty
